version: "3"
services:
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379

  db:
    container_name: postgres
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bpt-biller
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

  minio:
    container_name: minio
    image: bitnami/minio
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio:/data

volumes:
  db:
    driver: local
  minio:
    driver: local
